/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.BCrypt;
import controller.SearchAccount;
import controller.SearchFarm;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.Account;
import dao.AccountDAO;
import dao.CommuneDAO;
import dao.DistrictDAO;
import dao.FarmDAO;
import dao.OrganizationDAO;
import java.awt.Desktop;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.JFrame;
import model.Farm;
import model.NhaCungCap;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Admin
 */
public class FarmForm extends javax.swing.JInternalFrame {
// Model table cho farm
    private DefaultTableModel tblModel;
    private ArrayList<Farm> farms = (ArrayList<Farm>) FarmDAO.getInstance().selectAll();

    public FarmForm() {
        initComponents();
        UIManager.put("Table.showVerticalLines", true);
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        tblFarm.setDefaultEditor(Object.class, null); // Không cho chỉnh sửa trực tiếp trong bảng
        initTable();
        loadDataToTable(farms);
    }

    // Phương thức khởi tạo bảng
    public final void initTable() {
        tblModel = new DefaultTableModel();
        String[] headerTbl = new String[]{
            "Farm ID", "Tên farm", "Địa chỉ", "Huyện", "Xã", "Chủ sở hữu", "Latitude", "Longitude", "Tổ chức"
        };
        tblModel.setColumnIdentifiers(headerTbl);
        tblFarm.setModel(tblModel);
    }

    // Phương thức load dữ liệu farm vào bảng
    public void loadDataToTable(ArrayList<Farm> farms) {
        try {
            tblModel.setRowCount(0); // Xóa các dòng cũ trong bảng
            for (Farm farm : farms) {
                tblModel.addRow(new Object[]{
                    farm.getFarmId(),
                    farm.getFarmName(),
                    farm.getAddress(),
                    getDistrictName(farm.getDistrictId()),  // Lấy tên huyện theo districtId
                    getCommuneName(farm.getCommuneId()),    // Lấy tên xã theo communeId
                    farm.getOwner(),
                    farm.getLatitude(),
                    farm.getLongitude(),
                    getOrganizationName(farm.getOrganizationId())  // Lấy tên tổ chức theo organizationId
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Phương thức lấy thông tin huyện từ districtId
    private String getDistrictName(int districtId) {
        return DistrictDAO.getInstance().getDistrictNameById(districtId);
    }

    // Phương thức lấy thông tin xã từ communeId
    private String getCommuneName(int communeId) {
        return CommuneDAO.getInstance().getCommuneNameById(communeId);
    }

    // Phương thức lấy thông tin tổ chức từ organizationId
    private String getOrganizationName(int organizationId) {
        return OrganizationDAO.getInstance().selectById(organizationId).getName();
    }

    // Phương thức lấy farm được chọn từ bảng
    public Farm getFarmSelect() {
        int i_row = tblFarm.getSelectedRow();
        if (i_row >= 0) {
            int farmId = (int) tblFarm.getValueAt(i_row, 0); // Lấy farm_id từ cột đầu tiên
            return FarmDAO.getInstance().selectById(farmId);
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();
        btnEditAccount = new javax.swing.JButton();
        btnEditAccount1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        exportExcel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cbxSearchCategory = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFarm = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("THÊM TÀI KHOẢN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Họ và tên");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên đăng nhập");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mật khẩu");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Vai trò");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Thêm tài khoản");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jComboBox1, 0, 269, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jToolBar1.setRollover(true);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_40px.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdd);

        btnDeleteAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_40px.png"))); // NOI18N
        btnDeleteAccount.setText("Xoá");
        btnDeleteAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteAccount.setFocusable(false);
        btnDeleteAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccountActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDeleteAccount);

        btnEditAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_edit_40px.png"))); // NOI18N
        btnEditAccount.setText("Sửa");
        btnEditAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditAccount.setFocusable(false);
        btnEditAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAccountActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditAccount);

        btnEditAccount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-update-left-rotation-40.png"))); // NOI18N
        btnEditAccount1.setText("Đặt lại");
        btnEditAccount1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditAccount1.setFocusable(false);
        btnEditAccount1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditAccount1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAccount1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditAccount1);
        jToolBar1.add(jSeparator1);

        exportExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_spreadsheet_file_40px.png"))); // NOI18N
        exportExcel.setText("Xuất Excel");
        exportExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exportExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportExcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportExcelActionPerformed(evt);
            }
        });
        jToolBar1.add(exportExcel);

        jPanel2.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxSearchCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Tên Farm", "Huyện", "Xã" }));
        cbxSearchCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSearchCategoryActionPerformed(evt);
            }
        });
        jPanel3.add(cbxSearchCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 40));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 320, 40));

        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reset_25px_1.png"))); // NOI18N
        btnreset.setText("Làm mới");
        btnreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel3.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 170, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 720, 90));

        jScrollPane1.setBorder(null);

        tblFarm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Farm_ID", "Tên ", "Địa chỉ", "Huyện", "Xã", "Owner"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblFarm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblFarm.setGridColor(new java.awt.Color(204, 204, 204));
        tblFarm.setShowGrid(true);
        jScrollPane1.setViewportView(tblFarm);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1160, 620));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AddFarm a ;
        a = new AddFarm(this, (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this), rootPaneCheckingEnabled);
        a.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAccountActionPerformed
         // Kiểm tra nếu không có farm nào được chọn
        if (tblFarm.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn farm cần chỉnh sửa !");
        } else {
            // Mở form để chỉnh sửa farm
            UpdateFarm u = new UpdateFarm(this, (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this), rootPaneCheckingEnabled);
            u.setVisible(true);
        }
    }//GEN-LAST:event_btnEditAccountActionPerformed

    private void btnDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccountActionPerformed
            // Kiểm tra nếu không có farm nào được chọn
            // Kiểm tra nếu không có farm nào được chọn
            // Kiểm tra nếu không có farm nào được chọn
            if (tblFarm.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn farm cần xóa !");
            } else {
                
                // Lấy giá trị farmid từ dòng đã chọn
                int farmId = (int) tblFarm.getValueAt(tblFarm.getSelectedRow(), 0); // Cột farmid là cột đầu tiên

                // Xác nhận xóa farm
                int checkVl = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa farm này ?", "Xác nhận xóa farm", JOptionPane.YES_NO_OPTION);
                if (checkVl == JOptionPane.YES_OPTION) {
                    try {
                        // Gọi hàm xóa farm từ DAO
                        int result = FarmDAO.getInstance().delete(farmId);
                        if (result > 0) {
                            JOptionPane.showMessageDialog(this, "Xóa farm thành công!");
                            // Cập nhật lại bảng sau khi xóa
                            loadDataToTable((ArrayList<Farm>) FarmDAO.getInstance().selectAll());
                        } else {
                            JOptionPane.showMessageDialog(this, "Không thể xóa farm này!");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Lỗi khi xóa farm: " + e.getMessage());
                    }
                }
            }

    }//GEN-LAST:event_btnDeleteAccountActionPerformed

    private void exportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportExcelActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();
            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = wb.createSheet("Account");

                Row rowCol = sheet.createRow(0);
                for (int i = 0; i < tblFarm.getColumnCount(); i++) {
                    Cell cell = rowCol.createCell(i);
                    cell.setCellValue(tblFarm.getColumnName(i));
                }
                for (int j = 0; j < tblFarm.getRowCount(); j++) {
                    Row row = sheet.createRow(j + 1);
                    for (int k = 0; k < tblFarm.getColumnCount(); k++) {
                        Cell cell = row.createCell(k);
                        if (tblFarm.getValueAt(j, k) != null) {
                            cell.setCellValue(tblFarm.getValueAt(j, k).toString());
                        }
                    }
                }
                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(saveFile.toString());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_exportExcelActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        loadDataToTable(farms);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnEditAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAccount1ActionPerformed
        // TODO add your handling code here:
        if (tblFarm.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn farm cần chỉnh sửa!");
        } else {
            int check = JOptionPane.showConfirmDialog(this, "Bạn có muốn chỉnh sửa farm này?", "Chỉnh sửa", JOptionPane.YES_NO_OPTION);
            if (check == JOptionPane.YES_OPTION) {
                // Lấy thông tin farm cần chỉnh sửa từ bảng
                int row = tblFarm.getSelectedRow();
                int farmId = (Integer) tblFarm.getValueAt(row, 0);  // Giả sử farmId là cột đầu tiên trong bảng
                Farm farmToEdit = FarmDAO.getInstance().selectById(farmId);  // Lấy farm theo ID

                // Hiển thị các ô nhập liệu cho người dùng nhập thông tin mới
                String newFarmName = JOptionPane.showInputDialog(this, "Nhập tên farm mới:", farmToEdit.getFarmName());
                if (newFarmName == null || newFarmName.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Tên farm không được để trống!");
                    return;
                }

                String newAddress = JOptionPane.showInputDialog(this, "Nhập địa chỉ farm mới:", farmToEdit.getAddress());
                if (newAddress == null || newAddress.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Địa chỉ farm không được để trống!");
                    return;
                }

                String newOwner = JOptionPane.showInputDialog(this, "Nhập tên chủ sở hữu mới:", farmToEdit.getOwner());
                if (newOwner == null || newOwner.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Chủ sở hữu không được để trống!");
                    return;
                }

                // Cập nhật farm
                farmToEdit.setFarmName(newFarmName);
                farmToEdit.setAddress(newAddress);
                farmToEdit.setOwner(newOwner);

                try {
                    // Cập nhật farm vào cơ sở dữ liệu
                    FarmDAO.getInstance().update(farmToEdit);
                    JOptionPane.showMessageDialog(this, "Cập nhật farm thành công!");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Cập nhật farm không thành công!");
                }

                // Tải lại danh sách farm sau khi cập nhật
                ArrayList<Farm> farms = (ArrayList<Farm>) FarmDAO.getInstance().selectAll();
                loadDataToTable(farms);  // Hàm này sẽ làm mới bảng farm
            }
        }
    }//GEN-LAST:event_btnEditAccount1ActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
          triggerSearch();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void cbxSearchCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSearchCategoryActionPerformed
          triggerSearch();
    }//GEN-LAST:event_cbxSearchCategoryActionPerformed
    private void triggerSearch() {
        String searchCategory = cbxSearchCategory.getSelectedItem().toString(); // Lấy giá trị từ ComboBox
        String keyword = txtSearch.getText().trim(); // Lấy từ khóa từ TextField
        ArrayList<Farm> searchResults = new ArrayList<>();

        switch (searchCategory) {
            case "Tất cả":
                searchResults = (ArrayList<Farm>) SearchFarm.getInstance().searchAll(keyword);
                break;
            case "Mã Farm":
                searchResults = (ArrayList<Farm>) SearchFarm.getInstance().searchByFarmId(keyword);
                break;
            case "Tên Farm":
                searchResults = (ArrayList<Farm>) SearchFarm.getInstance().searchByFarmName(keyword);
                break;
            case "Tên Huyện":
                searchResults = (ArrayList<Farm>) SearchFarm.getInstance().searchByDistrictName(keyword);
                break;
            case "Tên Xã":
                searchResults = (ArrayList<Farm>) SearchFarm.getInstance().searchByCommuneName(keyword);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Vui lòng chọn loại tìm kiếm hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
        }

    // Load kết quả tìm kiếm vào bảng
    loadDataToTable(searchResults);
}

    public void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (IOException e) {
            System.out.println(e);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JButton btnEditAccount;
    private javax.swing.JButton btnEditAccount1;
    private javax.swing.JButton btnreset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxSearchCategory;
    private javax.swing.JButton exportExcel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JTable tblFarm;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    void loadDataToTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
